#! /bin/bash

files=""
prefix="lecture_"
for (( i=1; i<=$1; i++ ))
do
    files=$files$prefix$i","
done
files="${files%?},lecture_a1"
pdflatex "\def\myflag{$files} \input{main.tex}"
mv main.pdf lecture_notes_$1.pdf

files=""
prefix="exercises_"
for (( i=1; i<=$2; i++ ))
do
    files=$files$prefix$i","
done
files="${files%?}"
pdflatex "\def\isall{1} \def\myflag{$files} \input{exercise.tex}"
mv exercise.pdf exercises_with_solutions_$2.pdf

files=""
prefix="exercises_"
for (( i=1; i<=$1; i++ ))
do
    files=$files$prefix$i","
done
files="${files%?}"
pdflatex "\def\myflag{$files} \input{exercise.tex}"
mv exercise.pdf exercises_no_solutions_$1.pdf
