#! /bin/bash

if [ $1 == "full" ]
then
    pdflatex "\def\isall{1} \input{main.tex}"
else
    pdflatex "\def\isall{0} \input{main.tex}"
fi

#prefix="exercises_"
#for (( i=1; i<=$2; i++ ))
#do
#    files=$files$prefix$i","
#done
#files="${files%?}"
#pdflatex "\def\isall{1} \def\myflag{$files} \input{exercise.tex}"
#mv exercise.pdf exercises_with_solutions_$2.pdf
#
#files=""
#prefix="exercises_"
#for (( i=1; i<=$1; i++ ))
#do
#    files=$files$prefix$i","
#done
#files="${files%?}"
#pdflatex "\def\myflag{$files} \input{exercise.tex}"
#mv exercise.pdf exercises_no_solutions_$1.pdf
