#! /bin/bash

if [[ $2 == "notes" ]]
then
    pdflatex "\input{main.tex}"
    cp main.pdf lecture_notes_$1.pdf
else
    if [[ $# == 3 && $3 == "all" ]]
    then
	pdflatex "\def\isall{1} \input{exercise.tex}"
	cp exercise.pdf exercises_with_solutions_$1.pdf
    else
	pdflatex "\input{exercise.tex}"
	cp exercise.pdf exercises_no_solutions_$1.pdf
    fi
fi
